[target.aarch64-linux-android]
linker = "C:/Users/Eddie/AppData/Local/Android/Sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android35-clang.cmd"
rustflags = [
    "-L", "C:/Users/Eddie/AndroidStudioProjects/SecureLegion/opus-official/build/arm64-v8a",
    "-C", "link-arg=-Wl,-z,max-page-size=16384"
]

[target.armv7-linux-androideabi]
linker = "C:/Users/Eddie/AppData/Local/Android/Sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi35-clang.cmd"
rustflags = [
    "-L", "C:/Users/Eddie/AndroidStudioProjects/SecureLegion/opus-official/build/armeabi-v7a",
    "-C", "link-arg=-Wl,-z,max-page-size=16384"
]

[target.x86_64-linux-android]
linker = "C:/Users/Eddie/AppData/Local/Android/Sdk/ndk/android-ndk-r27c/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android35-clang.cmd"
rustflags = [
    "-L", "C:/Users/Eddie/AndroidStudioProjects/SecureLegion/opus-official/build/x86_64",
    "-C", "link-arg=-Wl,-z,max-page-size=16384"
]
