[target.aarch64-linux-android]
rustflags = ["-L", "C:/Users/Eddie/AndroidStudioProjects/SecureLegion/opus-official/build/arm64-v8a"]

[target.armv7-linux-androideabi]
rustflags = ["-L", "C:/Users/Eddie/AndroidStudioProjects/SecureLegion/opus-official/build/armeabi-v7a"]

[target.x86_64-linux-android]
rustflags = ["-L", "C:/Users/Eddie/AndroidStudioProjects/SecureLegion/opus-official/build/x86_64"]
